apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist
  labels:
    app: todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: erwiinsaputra/todolist
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: todolistsvc
spec:
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
